# Generated by Django 6.0.4 on 2026-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="sale_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="created_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
